name: Unit Tester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    name: Run Django Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.4
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create SQLite local database
        run: python manage.py migrate

      - name: Run unit tests
        run: python manage.py test
