name: Validate Language Info Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    name: Validate Language Info Files
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.4
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create SQLite local database
        run: python manage.py migrate

      - name: Run validate command
        run: python manage.py validatelanginfofiles
